### ISSUE TITLE
Optimize Current Misogyny Model to lower FP

### ISSUE THREAD

**Issue by malteserteresa** [opt-out-tools/study-online-misogyny#42]
**Objective**
Optimize currently MM so FP are as low as possible

**Description**
We do not want to be labeling as Misogynistic when they are not, thus we need to optimize our current model so this is not the case. What we need to determine is:

How good is the model at determining a misogynistic tweet?

How good is the model at differentiating a misogynistic tweet and a non-misogynistic tweet?

How many times does the model incorrectly predict that a misogynistic tweet is not misogynistic?

We are fousing on optimizing to lower the number of **false positives**

**Skills**
scikit-learn hyper-parameter optmization

**Tools**
Model, scikit-learn

**Time Estimation**

**Tasks**

- [ ] Download the model from s3 bucket using DVC
- [ ] Optimize using grid search etc.
- [ ] Save model to s3
