### ISSUE TITLE
Use AAE dialect detection model to identify dialects in dataset 

### ISSUE THREAD

**Issue by malteserteresa** [opt-out-tools/study-online-misogyny#43]
**Objective**
Identify Afro American English dialect in gold dataset. 

**Description**
Though dialectal language is increasingly abundant on social media, few resources exist for developing NLP tools to handle such language. We need to make sure we can identify the dialect to ensure we are not unintentionally biasing against this dialect.

**Skills**

**Dependencies**
The [model](http://slanglab.cs.umass.edu/TwitterAAE/), gold dataset

**Time Estimation**

**Tasks**

- [ ] Update the model to python 3+
- [ ] Test the model
- [ ] Use the model on the gold dataset
