### ISSUE TITLE
Relabel dataset for explicit misogyny

### ISSUE THREAD

**Issue by malteserteresa** [opt-out-tools/study-online-misogyny#50]
**Objective**
Improve our labeling of misogyny

**Description**
Our current model has flaws and one of them is due to the inconsistent labeling of misogyny. Thus we have decided to relabel the dataset, labeling only the comments that are explicitly misogynistic

**Skills**

**Tools**
Dependent on https://github.com/opt-out-tools/theory-of-online-misogyny/issues/12

**Time Estimation**

**Tasks**

- [ ] Decide what is explicit misogyny
- [ ] Label around 1000 comments
- [ ] Data augment using snorkel metal
