### ISSUE TITLE
Turn many Twitter objects to our format in .csv

### ISSUE THREAD

**Issue by malteserteresa** [opt-out-tools/study-online-misogyny#58]
**Objective**
Convert a twitter objects to a .csv file with the columns text, label

**Description**
A twitter object is a json has the content of the tweet in the "text" entry. We need to turn these twitter objects into the format for our scripts, which is a .csv file with the headings text, label (the label column will be filled out later).  

**Justification**
Twitters developer policy states that we may only distribute the tweet IDs when sharing datasets or if our dataset is under 50,000 we can share the tweet objects. 

We will choose to share the tweet objects because if we store the tweet IDs the dataset will degrade as tweets can be deleted retrospectively.

**Skills**
Understand Twitter APIs

**Dependencies**

**Time Estimation**

**Tasks**

- [ ] Decide on initial file type for multiple twitter objects (.json, .jsonl etc.)
- [ ] Convert objects to desired format
- [ ] Test: no duplication
- [ ] Consider how to do this to include user_id, reply_id etc., geo

**Comment by white-alistair** [comment]
Regarding the choice of initial file type, JSONL seems like a no-brainer compared to storing all of the tweets as one big JSON, considering the efficiency of being able to read and write tweets one by one. I couldn't find any significant drawback of using JSONL. There are other formats offering similar behaviour but nothing beyond JSONL.
