### ISSUE TITLE
Research best way to sample from Twitter

### ISSUE THREAD

**Issue by malteserteresa** [opt-out-tools/study-online-misogyny#61]
**Objective**
Understand the different APIs of Twitter, the objects they return and the algorithms these use to sample.

**Description**
We want to find the most misogynistic tweets for our predicted users. Our current approach of searching for tweets that mention our target users name is limited - the amount of misogynistic comments are very diluted. This task is the evaluate how limited that is, and to consider better solutions.

For this task, our end result is still classification

**Skills**

**Dependencies**
Our premium user account credentials

**Time Estimation**

**Tasks**

- [ ] General understanding of APIs and objects
- [ ] Understand sampling algorithms
- [ ] Test how diluted the search for names sampling method is and compare this to new ways of sampling
