### ISSUE TITLE
Build new logistic regression model with gold dataset

### ISSUE THREAD

**Issue by malteserteresa** [opt-out-tools/study-online-misogyny#62]
**Objective**
Build a new log reg model with our best dataset

**Description**
Our current model was not built from a complete dataset. We would like to rebuild this model to include all of our data.

**Skills**
Python, scikit-learn

**Dependencies**
gold dataset

**Time Estimation**
1+ hours

**Tasks**

- [ ] Decide preprocessing pipeline - check preprocess_text_pipelines.py
- [ ] Convert to vector form
- [ ] Build Log Reg
- [ ] Evaluate
- [ ] Optimize
- [ ] Save model
- [ ] Try with different preprocessing
