### ISSUE TITLE
Write Data Statement for the Gold Dataset

### ISSUE THREAD

**Issue by malteserteresa** [opt-out-tools/study-online-misogyny#64]
**Objective**
Write a README.md for our gold dataset.

**Description**
Currently our datasets are combined and confusing. We need to write a basic data statement, following the guidance in this [paper](https://www.aclweb.org/anthology/Q18-1041/). What we should include in a basic data statement is:

- Curation: need the search terms and the API used by twitter
- Annotator Demographic
- Speech Situation: time, place, modality, scripted, edited, async/sync
- Text Characteristics: genre, topic
- Other: such as collector demographics
- Provenance: other datasets in the dataset

**Skills**

**Dependencies**
gold dataset

**Time Estimation**

**Tasks**

- [ ] Find search terms used to collect data, annotator demographics
- [ ] Run topic modeling on scripts to identify text characteristics
- [ ] Find our date of collection
- [ ] Find out what data is contained within this dataset
