### ISSUE TITLE
Add docs/information on existing datasets

### ISSUE THREAD

**Issue by andra-pumnea** [opt-out-tools/study-online-misogyny#77]
**Objective**
The goal of this issue is to provide a survey of existing datasets targeting sexism in social media, along with a summary of the data collection and labeling mechanism and potential issues.

**Description**
If you want to add a dataset targeting hate speech or sexism, please make sure to include the info bellow:

- paper/blogpost that accompany the published dataset as title
- description
- data collection process
- labeling mechanism (should include details about annotation schema)
- potential issues
- learnings & comments

To include this information, edit the [datasets.md](https://github.com/opt-out-tools/study-online-misogyny/blob/master/data/datasets.md ) document.                                                                              

Make sure that each dataset is only included once (no duplicate info). But if you think that some info is missing from an entry, please add it! 

**Skills**
- paper reading & summarization

**Dependencies**
- no dependencies

**Time Estimation**
- 2 weeks

**Tasks**

- [x] Waseem, Zeerak, and Dirk Hovy. "Hateful symbols or hateful people? predictive features for hate speech detection on twitter."
- [x] Anzovino, Maria, Elisabetta Fersini, and Paolo Rosso. "Automatic identification and classification of misogynistic language on twitter."
- [ ] Troll Patrol Report

**Comment by teoguso** [comment]
@Ver2307 should we consider this issue solved? Or is it more of an ongoing work in progress? If it's too large a scope we should consider creating a wiki page. Let us know and we will close this if that's the case.

**Comment by Ver2307** [comment]
Hi,

I think it might still be of value to search for existing datasets that we could use. If you prefer to create another task for this, it’s fine with me. 

Von meinem iPhone gesendet

**Comment by teoguso** [comment]
> Hi, I think it might still be of value to search for existing datasets that we could use. If you prefer to create another task for this, it’s fine with me. Von meinem iPhone gesendet
> […](#)
> Am 16.05.2020 um 12:20 schrieb Matteo Guzzo ***@***.***>: @Ver2307 should we consider this issue solved? Or is it more of an ongoing work in progress? If it's too large a scope we should consider creating a wiki page. Let us know and we will close this if that's the case. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

It's just that "searching for existing datasets" is related to this repo but it doesn't imply actual action on the code. Therefore an issue is sort of an improper tool for the job. I would instead create a card in https://github.com/opt-out-tools/model-online-misogyny/projects/4.

**Comment by annabechang** [comment]
Hi, I am a phd student at UCDavis. I will be researching multilingual misogyny detection. I found this repo from PyData talk. Is it possible that I could get access to the data for research purposes? Or if it's already available is there any place you could point me to on how to download it? thanks.
